# Meeting Notes

## Mar 12 

Questions: 
 - Code for masters project class? 
 
 




## Mar 3

Questions:
 - Sign up for masters project class?
 - UW’s Summer Institutes Scholarship? Summer Institute in Statistical Genetics?


Todo for week10:


Notes:





## Feb 25:

 - Agenda:
Talk about papers?

 - Questions:
Signing up for the class?

 - Todo for week 9:

assumption of common taxa interaction is a strong assu

Chenyang didnt model the taxonomic dependence

Might need to involve Tom to talk about the phylogenic structre
there might be some conjecture or assumption about this.


Might use some sort of Distance to enhance the correlation structure



measure relationship between otu

Modelling the change of OTUs, the covariates also change over time.
Both things are changing over time
Impose a smooth structure.


Focus on how to model dependence part.

Varying coefficient model - look up
coefficients a function of time. (can use non-paremetric or semi parametric - smooth function )



pg 8


look at IMHP data - what kind of measurements they have.
longitudinal measurements for covariates and



extend this model to multiomics integration

Look up more papers about incorporating the phylogentic trees.
Look at IMHP and try to narrow down data.














## Feb 18 Meeting:
the GEE one model dependence  count data
the Beta one



FOCUS ON THESE PAPERS
Bayesian one
GEE one
Zhang 2018
Zhang 2020

Usually don't need to go though much of the simulation and application
Focus on the modeling part.
Think about model assumptions,



Chenyang used the GEE,
analysis between microbe and other data, and with microbiome data as response and link to other data.

For masters project:
Integrated microbiome human project
look at website for IMHP
look for relevant papers about the above
One or two papers per week.


Delia did a preliminary study on this project

Explore data to see if there is good
Tom might have some longitudinal data

Another collaboration with other longitudinal study might have some data.


When we meet next week, we can discuss the two papers i've read and thougths on models.
Send quick

In masters project might develop new model or use existing models on data.

Yuan has idea, but doesnt want to share yet until i've done literature review
